### PR TITLE
Examples for tosa dialect

### PR DESCRIPTION
**Pull request by Ris-Bali**
Example for tosa dialect

### CODE REVIEW

**Comment by zhanghb97** [comment]
Hi @Ris-Bali , thank you for working on this. I notice you are still gradually adding commits, so I wanted to know is this PR ready for review?

**Comment by Ris-Bali** [comment]
I was thinking of creating smaller prs for each dialect ; so as to avoid merge conflicts this one is for tosa if u want me to create a single pr for all the dialects ; I'll do it that way then . Thanks

**Comment by zhanghb97** [comment]
>  I was thinking of creating smaller prs for each dialect

@Ris-Bali This way is ok!

**Comment by Ris-Bali** [comment]
Closing this pr shifted to #37

**Pull request closed without merging**
