### PR TITLE
[DIP] Change resize2D interface

### PR DESCRIPTION
**Pull request by FlagerLee**
Change resize2D (in DIP.h) interface from
`inline MemRef<float, 2> Resize2D(Img<float, 2> *input, INTERPOLATION_TYPE type, std::vector<float> scalingRatios)`
to
`inline MemRef<float, 2> Resize2D(Img<float, 2> *input, INTERPOLATION_TYPE type, std::vector<uint> size)`
Now resize2D passes new image size instead of scaling ratio.

### CODE REVIEW

**Review by zhanghb97 — APPROVED** [review]
Thanks!

**Comment by zhanghb97** [comment]
ping @FlagerLee

**Comment by meshtag** [comment]
Our design was already capable of working with target image sizes directly, scaling ratios were not compulsorily required. 

OpenCV's python resize API can also optionally accept scaling ratios.

**Comment by meshtag** [comment]
I fear this change makes the interface lose some of its capabilities and would make our API diverge from the OpenCV one. If this change is not justified, I suggest reverting it. 

If you are unhappy about the intermediate floating point calculations, we can definitely find an alternative route for that. But I am not in favour of removing the option to provide scaling ratios.

**Comment by FlagerLee** [comment]
I see. I missed the function accept image size. But another question is these two functions' difference is the last argument type, which I don't think it is a good design(but of course this is another question).
You are right, please revert this commit @zhanghb97. Sorry for this.

**Comment by FlagerLee** [comment]
Besides, I recommend change Resize2D return type from Memref to Img. Do you have any thoughts on this?

**Comment by FlagerLee** [comment]
> I think we can change the return type for C++ interface of `Resize2D` to `img` from `memref`.

Yes, that's exactly what I want to do.

**Pull request merged**
