### PR TITLE
[dependencies] bump llvm to commit 6c59f0e1b0fb56c909ad7c9aad4bde37dc006ae0

### PR DESCRIPTION
**Pull request by Avimitin**
This PR bump the llvm submodules to commit 6c59f0e1b0fb56c909ad7c9aad4bde37dc006ae0 and add a nix flake to make the development more convenient for other developers.

### CODE REVIEW

**Comment by Avimitin** [comment]
## Current state:

- [x] Bump llvm and build buddy-mlir bintools upon the new llvm.
- [ ] Migrate all examples and tests to the latest buddy-mlir tools

**Comment by Avimitin** [comment]
Gemmini lowering code has been modified, who should I mention for reviewing these codes?

**Comment by Avimitin** [comment]
Bump is all done, and tests are all pass successfully. However the latest LLVM tablegen contains an unfixed bug. It is not easy to fix and we can only manually apply a patch to bypass this issue.

**Comment by zhanghb97** [comment]
@Avimitin Thanks!
Have merged to main.(https://github.com/buddy-compiler/buddy-mlir/commit/ce466bac3af5401341c29ffc34b11f235e58546d)

**Pull request closed without merging**
