### PR TITLE
Examples for operations for SCF dialect

### PR DESCRIPTION
**Pull request by Ris-Bali**
Examples of Operations in SCF dialect

### CODE REVIEW

**Comment by Ris-Bali** [comment]
@zhanghb97 This pr is ready for review

**Comment by meshtag** [comment]
Please remove unnecessary white-spaces from files (Add some extra ones at the end of each file too).

**Comment by Ris-Bali** [comment]
Done! Pls review.

**Comment by meshtag** [comment]
@Ris-Bali , there are still some formatting suggestions from my side (you might refer existing files in `examples` directory): 
1. Please separate variable initialization and `for` loops with a blank line.
2. Please leave only **one** blank line at the end of each file.

I'll try to build your branch in my local system before EOD and share my suggestions (if any).

**Comment by Ris-Bali** [comment]
Okay will make these changes in both the prs

**Review by meshtag — APPROVED** [review]
@Ris-Bali , I have made some minor changes in formatting to save us the trouble of going through each and every small change. 
@zhanghb97 , I have verified this PR's build locally and it seems to work fine.

**Comment by zhanghb97** [comment]
@Ris-Bali @meshtag Thanks a lot! One more small suggestion, I think we are using the two spaces for indentation in MLIR files. So please modify the indentation of MLIR files in the PR, and LGTM for other parts. So sorry for this back and force format modification, I hope we can use a consistent format 😁

**Comment by Ris-Bali** [comment]
> @Ris-Bali , I have made some minor changes in formatting to save us the trouble of going through each and every small change (Please modify #32 on similar lines). @zhanghb97 , I have verified this PR's build locally and it seems to work fine.

Thanks will modify #32 as well

**Comment by Ris-Bali** [comment]
I don't know how but suddenly there is a merge conflict .

**Comment by Ris-Bali** [comment]
Closing this pr shifted to #37

**Pull request closed without merging**
