### PR TITLE
fix batchMatMul-opt pass bug

### PR DESCRIPTION
**Pull request by ShiHaoGao**

### CODE REVIEW

**Review by zhanghb97 — COMMENTED** [review]
MLIR files need FileCheck for `ninja check-buddy`, see MLIRConvolution cases for details.

BTW, the folder name change to `BuddyMatmul`

**Comment by ShiHaoGao** [comment]
The result of `ninja check-buddy` remains failed, becase of `-batchmatmul-optimize`'s bugs.

**Comment by zhanghb97** [comment]
image
It also fails existing Linalg cases. We need to dig deep to find the real reason.

**Comment by zhanghb97** [comment]
FYI - I have fixed the bug: https://github.com/buddy-compiler/buddy-mlir/commit/7e796f63ffd710049403429b60032016433ddd1f

**Pull request closed without merging**
