### PR TITLE
[Linalg to Gemmini][Hardware config]Add Linalg to Gemmini pass and Hardware config

### PR DESCRIPTION
**Pull request by linuxlonelyeagle**

### CODE REVIEW

**Comment by linuxlonelyeagle** [comment]
## This pr contains the following
* Linalg to Gemmini pass 
   Includes the new Linalg op to Gemmini.
* Gemmini's performance tests
* Hardware config
  For examples of how to specify Gemmini's configuration, you can check out `conv_2d_nhwc_hwcf` and `conv_2d_nchw_fchw` in the `buddy-mlir/examples/GemminiDialect/`

**Review by zhanghb97 — APPROVED** [review]
Thanks!

**Comment by zhanghb97** [comment]
@linuxlonelyeagle Please resolve the conflict.

**Comment by linuxlonelyeagle** [comment]
> @linuxlonelyeagle Please resolve the conflict.

I have make it.

**Pull request merged**
