### PR TITLE
Search for ANTLR only if samples compilation enabled

### PR DESCRIPTION
**Pull request by ArtemSkrebkov**
## Motivation
Currently, developers do not need ANTLR if they build it with examples disabled.

### CODE REVIEW

**Comment by ArtemSkrebkov** [comment]
@zhanghb97 

Please take a look. You had an idea about `BUDDY_FRONTEND_SUPPORT=ON` but I didn't find such the option to re-use.

**Comment by zhanghb97** [comment]
> You had an idea about BUDDY_FRONTEND_SUPPORT=ON but I didn't find such the option to re-use.

Yes! Then let's re-use `BUDDY_DSL_EXAMPLES` as the name.

**Comment by ArtemSkrebkov** [comment]
Right. I missed the fact of using it in DSL samples.
Fixed.

**Comment by zhanghb97** [comment]
Thanks!

**Pull request merged**
